# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard :jasmine do
  watch(%r{js/specs/javascripts/spec\.(js\.coffee|js|coffee)$}) { 'spec/javascripts' }
  watch(%r{js/specs/.+_spec\.(js\.coffee|js|coffee)$})
  watch(%r{js/specs/fixtures/.+$})
  watch(%r{app/assets/javascripts/(.+?)\.(js\.coffee|js|coffee)(?:\.\w+)*$}) { |m| "spec/javascripts/#{ m[1] }_spec.#{ m[2] }" }
end
